# Form implementation generated from reading ui file 'design_frame\qt_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QBrush, QColor, QIcon, QLinearGradient, QPalette
from PyQt6.QtWidgets import QApplication, QMainWindow, QListWidgetItem, QCheckBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Routine Checking")
        MainWindow.resize(905, 702)

        # Create a gradient for the background (left to right)
        gradient = QLinearGradient(0, 0, MainWindow.width(), 0)
        gradient.setColorAt(0, QColor(180, 180, 180))  # Start color (gray)
        gradient.setColorAt(1, QColor(250, 250, 250))  # End color (light gray)

        # Set the background gradient for the entire main window
        palette = QPalette()
        palette.setBrush(QtGui.QPalette.ColorRole.Window, QBrush(gradient))
        MainWindow.setPalette(palette)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_button = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_button.setGeometry(QtCore.QRect(20, 100, 141, 541))
        self.widget_button.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"background-color: rgb(0, 6, 38);")
        self.widget_button.setObjectName("widget_button")

        # Add button
        self.add_button = QtWidgets.QPushButton(parent=self.widget_button)
        self.add_button.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.add_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.add_button.setObjectName("add_button")

        # Delete button
        self.delete_button = QtWidgets.QPushButton(parent=self.widget_button)
        self.delete_button.setGeometry(QtCore.QRect(20, 70, 101, 31))
        self.delete_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete_button.setObjectName("delete_button")

        # Delete all button
        self.delete_all_button = QtWidgets.QPushButton(parent=self.widget_button)
        self.delete_all_button.setGeometry(QtCore.QRect(20, 130, 101, 31))
        self.delete_all_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.delete_all_button.setObjectName("delete_all_button")

        # Edit button
        self.edit_button = QtWidgets.QPushButton(parent=self.widget_button)
        self.edit_button.setGeometry(QtCore.QRect(20, 190, 101, 31))
        self.edit_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_button.setObjectName("edit_button")

        # Export button
        self.export_button = QtWidgets.QPushButton(parent=self.widget_button)
        self.export_button.setGeometry(QtCore.QRect(20, 400, 101, 31))
        self.export_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.export_button.setObjectName("export_button")

        # Import button
        self.import_button = QtWidgets.QPushButton(parent=self.widget_button)
        self.import_button.setGeometry(QtCore.QRect(20, 350, 101, 31))
        self.import_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.import_button.setObjectName("import_button")

        # Analysis button
        self.analysis_button = QtWidgets.QPushButton(parent=self.widget_button)
        self.analysis_button.setGeometry(QtCore.QRect(20, 250, 101, 31))
        self.analysis_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.analysis_button.setObjectName("analysis_button")

        # Frame analysis
        self.frame_analysis = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_analysis.setGeometry(QtCore.QRect(179, 99, 361, 541))
        self.frame_analysis.setStyleSheet("background-color: rgb(0, 6, 38);")
        self.frame_analysis.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_analysis.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_analysis.setObjectName("frame_analysis")
        self.widget_piece_chart = QtWidgets.QWidget(parent=self.frame_analysis)
        self.widget_piece_chart.setGeometry(QtCore.QRect(20, 50, 321, 201))
        self.widget_piece_chart.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_piece_chart.setObjectName("widget_piece_chart")
        self.widget_line_chart_7_days = QtWidgets.QWidget(parent=self.frame_analysis)
        self.widget_line_chart_7_days.setGeometry(QtCore.QRect(20, 300, 321, 201))
        self.widget_line_chart_7_days.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_line_chart_7_days.setObjectName("widget_line_chart_7_days")

        # Frame to do list
        self.frame_todolist = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_todolist.setGeometry(QtCore.QRect(559, 99, 331, 321))
        self.frame_todolist.setStyleSheet("background-color: rgb(0, 6, 38);")
        self.frame_todolist.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_todolist.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_todolist.setObjectName("frame_todolist")
        # Widget to do list
        self.widget_todolist = QtWidgets.QListWidget(parent=self.frame_todolist)
        self.widget_todolist.setGeometry(QtCore.QRect(10, 10, 311, 301))
        self.widget_todolist.setObjectName("widget_todolist")

        # Frame calendar
        self.frame_calendar = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_calendar.setGeometry(QtCore.QRect(559, 439, 331, 201))
        self.frame_calendar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_calendar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_calendar.setObjectName("frame_calendar")
        self.widget_calendar = QtWidgets.QCalendarWidget(parent=self.frame_calendar)
        self.widget_calendar.setGeometry(QtCore.QRect(1, 0, 331, 201))
        self.widget_calendar.setMinimumSize(QtCore.QSize(331, 201))
        self.widget_calendar.setMaximumSize(QtCore.QSize(331, 16777215))
        self.widget_calendar.setStyleSheet("background-color: rgb(0, 6, 38);\n"
"color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(54, 69, 79);\n"
"selection-background-color: rgb(112, 128, 144);\n"
"border-color: rgb(0, 0, 127);\n"
"")
        # Widget calendar
        self.widget_calendar.setObjectName("widget_calendar")
        self.frame_user_info = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_user_info.setGeometry(QtCore.QRect(730, 10, 161, 80))
        self.frame_user_info.setStyleSheet("background-color: rgb(0, 6, 38);")
        self.frame_user_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_user_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_user_info.setObjectName("frame_user_info")

        # Lable avatar
        self.frame_avatar = QtWidgets.QFrame(parent=self.frame_user_info)
        self.frame_avatar.setGeometry(QtCore.QRect(69, 10, 81, 61))
        self.frame_avatar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_avatar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_avatar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_avatar.setObjectName("frame_avatar")
        self.update_avatar_button = QtWidgets.QPushButton(parent=self.frame_user_info)
        # self.update_avatar_button.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.update_avatar_button.setStyleSheet("font: 9pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.update_avatar_button.setObjectName("update_avatar_button")

        # Frame app title
        self.frame_app_title = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_app_title.setGeometry(QtCore.QRect(19, 10, 691, 81))
        self.frame_app_title.setStyleSheet("background-color: rgb(0, 6, 38);")
        self.frame_app_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_app_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_app_title.setObjectName("frame_app_title")
        self.textEdit = QtWidgets.QTextEdit(parent=self.frame_app_title)
        self.textEdit.setGeometry(QtCore.QRect(110, 10, 461, 61))
        self.textEdit.setStyleSheet("font: 28pt \"Rockwell\";")
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        # Menu bar
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 22))
        self.menubar.setObjectName("menubar")
        self.menuRoutine_checking = QtWidgets.QMenu(parent=self.menubar)
        self.menuRoutine_checking.setObjectName("menuRoutine_checking")
        self.menuDetails = QtWidgets.QMenu(parent=self.menubar)
        self.menuDetails.setObjectName("menuDetails")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menubar.addAction(self.menuRoutine_checking.menuAction())
        self.menubar.addAction(self.menuDetails.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Routine Checking"))
        MainWindow.setWindowIcon(QIcon("resources/window_icon.png"))
        self.add_button.setText(_translate("MainWindow", "Add Routine"))
        self.delete_button.setText(_translate("MainWindow", "Delete Routine"))
        self.edit_button.setText(_translate("MainWindow", "Edit Routine"))
        self.export_button.setText(_translate("MainWindow", "Export"))
        self.import_button.setText(_translate("MainWindow", "Import"))
        self.analysis_button.setText(_translate("MainWindow", "Analysis"))
        self.delete_all_button.setText(_translate("MainWindow", "Delete All"))
        self.update_avatar_button.setText(_translate("MainWindow", "Update"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Rockwell\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; color:#ffffff;\">Routine Checking App</span></p></body></html>"))
        self.menuRoutine_checking.setTitle(_translate("MainWindow", "Routine checking"))
        self.menuDetails.setTitle(_translate("MainWindow", "Details"))
